import type { SnapshotPartnerSkill } from "./data";
import type { Locale } from "./taxonomy";

const ES_NAMES: Record<string, string> = {
  "Aegis Shield": "Escudo Égida",
  "Aerial Marauder": "Saqueador aéreo",
  "Aerial Missile": "Misil aéreo",
  "Amicable Holy Dragon": "Dragón sagrado amistoso",
  "Angry Shark": "Tiburón furioso",
  Antigravity: "Antigravedad",
  "Aqua Spout": "Chorro acuático",
  "Aurora Guide": "Guía de la aurora",
  "Best Boy": "Buen chico",
  "Big Stretch": "Gran estiramiento",
  "Birds of a Feather": "Tal para cual",
  "Black Ankylosaur": "Anquilosaurio negro",
  "Blade of Uncontrolled Passion": "Hoja de pasión descontrolada",
  "Blessing of Purification": "Bendición de purificación",
  "Blessing of the Flower Spirit": "Bendición del espíritu floral",
  "Cat Helper": "Gato ayudante",
  "Charging Shell": "Caparazón cargado",
  "Charming Fish": "Pez encantador",
  "Chilled Whale Cruiser": "Ballena crucero gélida",
  Chillswitch: "Cambio gélido",
  "Cold Bomb": "Bomba gélida",
  "Corruption Laser": "Láser de corrupción",
  "Cozy Whale Cruiser": "Ballena crucero acogedora",
  "Dark Gleam Strike": "Golpe de brillo oscuro",
  "Dark Knight of the Abyss": "Caballero oscuro del abismo",
  "Dark Knowledge": "Conocimiento oscuro",
  "Dark-Nester": "Anidador oscuro",
  "Death-Cheating Feline": "Felino tramposo de la muerte",
  "Dig, Dog! Dig!": "¡Cava, perrito, cava!",
  "Dragon Kaiser": "Káiser dragón",
  "Dream Chaser": "Cazador de sueños",
  "Eggbomb Launcher": "Lanzahuevos explosivo",
  "Electro Hunter": "Cazador eléctrico",
  "Ember Chamber": "Cámara de brasas",
  "Ferocious Thunder Dragon": "Dragón del trueno feroz",
  "Flame Lantern": "Linterna flamígera",
  "Flame Wing": "Ala flamígera",
  Fluffy: "Esponjoso",
  "Fluffy Flutterer": "Aleteador esponjoso",
  "Fluffy Wool": "Lana esponjosa",
  "Fortified Shell": "Caparazón fortificado",
  "Fragrant Dragon": "Dragón fragante",
  "Fried Squid": "Calamar frito",
  "Friend of Earth": "Amigo de la tierra",
  "Frozen Gleam Strike": "Golpe de brillo gélido",
  "Full-Power Gorilla Mode": "Modo gorila a plena potencia",
  "Fuzzy Fairy": "Hada peluda",
  "Galeclaw Glider": "Planeador Galeclaw",
  "Glorious Mist": "Niebla gloriosa",
  "Golden Harvest": "Cosecha dorada",
  "Grass Weaver": "Tejedor de hierba",
  "Grassland Speedster": "Velocista de la pradera",
  "Grimoire Collector": "Coleccionista de grimorios",
  "Grinning Death": "Muerte sonriente",
  "Grounded Archer": "Arquero arraigado",
  "Guardian of the Desert": "Guardián del desierto",
  "Hard Armor": "Armadura resistente",
  "Harvest Goddess": "Diosa de la cosecha",
  "Hawk Eye": "Ojo de halcón",
  "Heart Drain": "Drenaje de corazón",
  "Helper Bunny": "Conejita ayudante",
  "Herbil Pulse": "Pulso de Herbil",
  "Ice Steed": "Corcel de hielo",
  "Jelliette Drop": "Botín de Jelliette",
  "King of Fluff": "Rey de la pelusa",
  "Lady of Lightning": "Dama del relámpago",
  "Lantern Enchantment": "Encantamiento de linterna",
  "Lava Spout": "Chorro de lava",
  "Leap Stance": "Postura de salto",
  "Liberated Pterosaur": "Pterosaurio liberado",
  "Life Steal": "Robo de vida",
  "Long-Sleeved Hurray": "Hurra de mangas largas",
  "Magma Kaiser": "Káiser magma",
  "Magma Overload": "Sobrecarga magmática",
  "Masonry Archelon": "Arquelón albañil",
  "Messenger of Death": "Mensajero de la muerte",
  "Meteor Mania": "Fiebre meteórica",
  "Meteor Wings": "Alas meteóricas",
  "Mining Assistance": "Asistencia minera",
  "Night Dancer": "Bailarín nocturno",
  "Nightmare Iris": "Iris de pesadilla",
  "Nightmare Stare": "Mirada de pesadilla",
  "Peacock Pounce": "Salto del pavo real",
  "Power Stone": "Piedra de poder",
  "Princess Gaze": "Mirada de princesa",
  "Queen Bee Command": "Mando de abeja reina",
  "Resonant Guardian": "Guardián resonante",
  "Rollin' Full Oil": "Rodillo de aceite",
  "Sacred Barrier": "Barrera sagrada",
  "Sand Swimmer": "Nadador de arena",
  "Scorpion Sonar": "Sonar de escorpión",
  "Seared Fish Fillet": "Filete de pescado chamuscado",
  "Selfless Discipline": "Disciplina abnegada",
  "Sentinel of the Great Sea": "Centinela del Gran Mar",
  "Shadow Stance": "Postura sombría",
  "Shiny Hauler": "Transportista brillante",
  "Shot-Nyan Mode": "Modo Shot-Nyan",
  "Skilled Fingers": "Dedos habilidosos",
  "Sky Dragon Affection": "Afecto del dragón celeste",
  "Snake's Sagacity": "Sagacidad de serpiente",
  "Snow Shepherd": "Pastor de la nieve",
  "Soil Improver": "Mejorador del suelo",
  "Soothing Shower": "Ducha reconfortante",
  "Soul Collector": "Recolector de almas",
  "Spikey Carrier": "Transportista espinoso",
  "Static Electricity": "Electricidad estática",
  "Steel Guardian Mode": "Modo guardián de acero",
  "Sticky Princess": "Princesa pegajosa",
  "Stormbringer Lava Dragon": "Dragón de lava portador de tormentas",
  "Stormbringer Sea Dragon": "Dragón marino portador de tormentas",
  "Swift Deity": "Deidad veloz",
  "Thunder Dragon": "Dragón del trueno",
  "Tiny Spark": "Pequeña chispa",
  "Unknown Intruder": "Intruso desconocido",
  "Untainted Maiden": "Doncella inmaculada",
  "Unyielding Storm Commander": "Comandante de la tormenta inquebrantable",
  "Waterwing Dance": "Danza de alas acuáticas",
  "Wings of Thunder": "Alas del trueno",
  "Wolf of the Sun": "Lobo del sol",
  "Worker Bee": "Abeja obrera",
  "Wriggling Weasel": "Comadreja ondulante",
  "Zephyr Glider": "Planeador céfiro",
};

function clean(value: string): string {
  return value
    .replace(/<[^>]*>/g, "")
    .replace(/\[\[File:[^\]]+\]\]/gi, "")
    .replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2")
    .replace(/\[\[([^\]]+)\]\]/g, "$1")
    .replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
}

function localizeDescription(value: string): string {
  let text = clean(value);
  const replacements: [RegExp, string][] = [
    [/hitting an enemy with a bullet increases the Attack and Defense of the Pal fighting alongside you by 1% for 5 seconds\. This effect stacks up to 30 times\./gi, "cada bala que impacta a un enemigo aumenta el Ataque y la Defensa del Pal que combate a tu lado un 1% durante 5 segundos. El efecto se acumula hasta 30 veces."],
    [/appears near the player\./gi, "aparece junto al jugador."],
    [/attacks hostile enemies with/gi, "ataca a los enemigos hostiles con"],
    [/These bullets will not reduce the target's Health below 1\./gi, "Estas balas no reducen la Salud del objetivo por debajo de 1."],
    [/the Pal fighting alongside you/gi, "el Pal que combate a tu lado"],
    [/for a limited time/gi, "durante un tiempo limitado"],
    [/This effect stacks up to ([0-9]+) times/gi, "El efecto se acumula hasta $1 veces"],
    [/the player's ([A-Za-z ]+)/gi, "la $1 del jugador"],
    [/the player's and Pals' damage/gi, "el daño del jugador y sus Pals"],
    [/the player and Felbat/gi, "el jugador y Felbat"],
    [/restores ([0-9]+)% of the player's Health/gi, "restaura un $1% de la Salud del jugador"],
    [/reduces the effects of gravity on the player/gi, "reduce los efectos de la gravedad sobre el jugador"],
    [/While in party,/g, "Mientras está en el equipo,"],
    [/While in team,/g, "Mientras está en el equipo,"],
    [/While fighting together,/g, "Mientras combate junto a ti,"],
    [/When activated,/g, "Al activarla,"],
    [/Can be ridden as a flying mount\.?/g, "Se puede montar como montura voladora."],
    [/Can be ridden\.?/g, "Se puede montar."],
    [/increases the player's/g, "aumenta el"],
    [/increases player's/g, "aumenta el"],
    [/increases Attack of/g, "aumenta el ataque de"],
    [/increases Defense of/g, "aumenta la defensa de"],
    [/increases damage/g, "aumenta el daño"],
    [/increases damage dealt/g, "aumenta el daño infligido"],
    [/reduces the Partner Skill cooldowns/g, "reduce los enfriamientos de las Habilidades de Compañero"],
    [/reduces their Attack/g, "reduce su ataque"],
    [/attacks targeted enemy with/g, "ataca al enemigo objetivo con"],
    [/While mounted,/g, "Mientras está montada,"],
    [/while mounted/g, "mientras está montada"],
    [/the player's attack type/g, "el tipo de ataque del jugador"],
    [/player and party Pals/g, "el jugador y los Pals del equipo"],
    [/Pals drop more items when defeated/g, "los Pals obtienen más objetos al derrotar enemigos"],
    [/damage to enemy weak points/g, "daño a los puntos débiles del enemigo"],
    [/damage to enemies afflicted with/g, "daño a enemigos afectados por"],
    [/damage while the target remains/g, "daño mientras el objetivo siga afectado por"],
    [/This Pal's Attack increases/g, "El ataque de este Pal aumenta"],
    [/Attack and Defense/g, "Ataque y Defensa"],
    [/Attack/g, "Ataque"],
    [/Defense/g, "Defensa"],
    [/Movement Speed/g, "Velocidad de movimiento"],
    [/Health/g, "Salud"],
    [/damage/g, "daño"],
    [/party Pals/g, "Pals del equipo"],
    [/Dark Pals/g, "Pals Oscuros"],
    [/Dragon Pals/g, "Pals Dragón"],
    [/Fire Pals/g, "Pals de Fuego"],
    [/Grass Pals/g, "Pals de Planta"],
    [/Water Pals/g, "Pals de Agua"],
    [/Electric Pals/g, "Pals Eléctricos"],
    [/Ice Pals/g, "Pals de Hielo"],
    [/Ground Pals/g, "Pals de Tierra"],
    [/Neutral Pals/g, "Pals Neutrales"],
    [/while in party/g, "mientras está en el equipo"],
    [/does not stack/gi, "no se acumula"],
    [/Does not stack/g, "No se acumula"],
  ];
  for (const [pattern, replacement] of replacements) text = text.replace(pattern, replacement);
  return text.replace(/\(no se acumula\)/g, "(No se acumula)");
}

export function localizePartnerSkill(skill: SnapshotPartnerSkill, locale: Locale) {
  if (locale === "en") return { name: skill.name, description: clean(skill.description) };
  return {
    name: ES_NAMES[skill.name] ?? skill.name,
    description: localizeDescription(skill.description),
  };
}
